# Generated by Django 3.0.5 on 2022-05-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20220506_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='text',
            new_name='pizza_name',
        ),
    ]
