# Generated by Django 3.0.5 on 2022-05-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20220506_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='date_added',
        ),
    ]
