# Generated by Django 3.0.5 on 2022-05-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_remove_topping_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='text',
            new_name='topping_name',
        ),
    ]
