# Generated by Django 3.0.5 on 2022-05-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_remove_topping_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topping',
            name='topping_name',
            field=models.TextField(max_length=200),
        ),
    ]
